name: Trigger auto deployment for skincare-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/skincare-frontend-AutoDeployTrigger-0ce43fb5-ecb2-42e7-944d-17b3b97514a7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SKINCAREFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SKINCAREFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SKINCAREFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}frontend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: skincare.azurecr.io
          registryUsername: ${{ secrets.SKINCAREFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SKINCAREFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: skincare-frontend
          resourceGroup: skincare
          imageToBuild: skincare.azurecr.io/skincare-frontend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


